### PR TITLE
Cmd

### PR DESCRIPTION
**Pull request by vtrlx**
Fixes some bugs, adds a new option to point to the student logins instead of employee (seems very finicky for me), and made it so debug/verbose settings are command-line based instead of in config.py

### CODE REVIEW

**Comment by dbs** [comment]
So, a couple of things:
1. Let the defaults still be set in the config file. That way, the command line arguments can override the defaults, but in situations where you're not using the command line at all (e.g. fastcgi) you can still change the details via a config file instead of having to monkey with your core script.
2. We should really use the configparser module instead of a config.py file for all configurable settings.
3. Rather than rolling your own command line argument parser, please use one of the core python modules that already do that. I recommend optparse. Good to know how to do it yourself in this case, but if the module is in core let's use it!

**Comment by dbs** [comment]
Oh, and it makes sense to move the secret into a config.ini file too, so that all config options are on one spot. Remember to update the docs in the same commit!

**Comment by vtrlx** [comment]
Hmmm. The secret is what's used to sign cookies, which might be better off _not_ being put on git. No?

**Comment by dbs** [comment]
The standard approach is to either put in a dummy secret with a big comment saying "CHANGE THIS!" or to leave it null and have a runtime check that throws an exception that says "Hey dummy you didn't read the docs and need to set the secret". I like the latter approach personally (with a comment in the config file as well: belt and suspenders)

**Pull request closed without merging**
